### ISSUE TITLE
Sweden Sundays shown as Public Holidays 

### ISSUE THREAD

**Issue by Saad-nvd** [vacanza/holidays#2153]
### Expected Behavior

For Country: Sweden (SE), Sunday is a weekend day.

### Actual Behavior

For Country: Sweden (SE), Sunday is being shown as Public Holiday.

### Steps to Reproduce the Problem

Provide an unambiguous set of steps to reproduce this bug.
Include code to reproduce, if relevant.

  1. country_holidays = holidays.country_holidays('SE', years=[2024 2025], categories='public')
  2. Observe output
 ![image](https://github.com/user-attachments/assets/fc25a337-2934-403e-b0c9-5436b462150f)

### Environment

- OS: Windows
- Python version: 3.12
- holidays version: 0.55

### Additional Context

Sunday a weekend day for Sweden is being shown as Public Holiday which is not correct.
![Sweden Sunday issue](https://github.com/user-attachments/assets/9a59ea88-7e80-4c0e-8dc8-b25099a77b29)

**Comment by arkid15r** [comment]
It's kind of an expected behavior we've had for a while. Please see https://github.com/vacanza/holidays/issues/1654 and https://github.com/vacanza/holidays/issues/2072 for more context.

At this moment I don't think it's going to change at least for `v0`. I can only suggest using `include_sundays=False` which is defined [here](https://github.com/vacanza/holidays/blob/78a48a083ca293c37c73fdec635cb59fccafa689/holidays/countries/sweden.py#L39) (Norway has it too but it's False by default). I promise to revisit this for `v1` though.

Please re-open if you have any questions/comments.

**Comment by Saad-nvd** [comment]
Thank you for the answer. When can we expect v1?

**Comment by arkid15r** [comment]
> Thank you for the answer. When can we expect v1?

Some time 2025 depending on our funding search outcomes. 

// Just to make sure we are on the same page -- v0 version already allows you to change the behavior for Sweden Sundays.
